Algoritmo "semnome"

Var
   valor, Fatorial, j: inteiro
   continua: caractere
Inicio
   repita



      escreva ("De qual valor deseja fazer fatorial?: ")
      leia (valor)
      Fatorial<- 1
      para valor de 1 até valor faca
         Fatorial <-Fatorial * valor
      fimpara
      escreval("o fatorial de", valor, "é", Fatorial)
      escreva ("quer fazer de novo ? s/n: ")
      leia (continua)
      limpatela
   ate continua = "n"

Fimalgoritmo
//escreval o bagulho fica em pe