Algoritmo "TESTE"

Var
NOTA1, NOTA2, NOTA3, NOTA4, MEDIA: Real
ALUNO: Caracter


Inicio
      Escreva ("Digite o nome do aluno: ")
      leia (ALUNO)
      Escreva ("Digite a primeira nota: ")
      Leia (NOTA1)
      Escreva ("Digite a segunda nota: ")
      leia (NOTA2)
      escreva ("digite a terceira nota: ")
      leia (NOTA3)
      escreva ("digite a quarta: ")
      leia (NOTA4)
      MEDIA<- (NOTA1+NOTA2+NOTA3+NOTA4) /4
      ESCREVAL("SUA MEDIA E: ", MEDIA)


Fimalgoritmo